### ISSUE TITLE
Rocket Physical Specifications

### ISSUE THREAD

**Issue by bariscihanoglu** [baftii/MPU6050#1]
Hello, I was wondering if I can get specifications of the rocket and PCB you used?

I was aiming to create my own. Can I achieve that?

Thanks!

**Comment by baftii** [comment]
Firstly, everyone can build a rocket if they devote time to it.

However, this library is not thoroughly related with rocket. We were planning to use MPU9250 for our rocket as a 9-DOF inertial measurement unit. But, its very old sensor and it is obsolete so we can't find it for our PCB in stocks. (Some of the companies have it but they are selling it as a price of diamond!) After a team discussion, we decided to use BNO055 sensor. Unfortunately, I had written a library for MPU6050/9250 before this discussion, so I added it here as a memory, thinking that this library should not be rubbish.

Also, you surprised me. I woke up in the morning and before I had uploaded all the files related to the library, I saw your topic in my e-mail. I think you fell in love with me. Doğa can jealous about that be careful.

As for your question, I hope that I will answer it in Finland next semester. ★⌒ヽ( ͡° ε ͡°)♥
